### PR TITLE
fix syntax error

### PR DESCRIPTION
**Pull request by ghost**
when running the script i get the following error:
SyntaxError: illegal character @ https://zininzinin.github.io/AutoTrimps/AutoTrimps2.js:399

this should fix it

### CODE REVIEW

**Comment by spindrjr** [comment]
What browser and version are you using? This line uses some special template string something or rather (the ${} part) that I think is not supported some places. This is why it's enclosed in backticks.

**Comment by ghost** [comment]
i'm using pale moon version 26.1.1 (x86)

**Comment by spindrjr** [comment]
Yea it looks like it just doesn't support some of the newer javascript standard stuff. If you can make some sort of polyfill for it I can include it. I have some ideas for use of this particular type of coding so I may use more of it in the future.

**Comment by ghost** [comment]
can't seem to find a polyfill that doesn't require compiling the source through node.js modules or significant code changes. closing this for now. i'll just run it under firefox till pale moon catches up with ES6 support

**Pull request closed without merging**
